### ISSUE TITLE
Getting error '(ModuleNotFoundError: No module named 'search') " while installing

### ISSUE THREAD

**Issue by mdp0999** [nlx-group/LX-WordNetBrowser#1]
Hi........ I am very interested to develope telugu wordnet. Please anyone here help me to install this software and translate into telugu.
here I am getting error while executing in local mode by using below command
python manage.py runserver localhost:1234

errors:

  File "/home/mdp/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mdp/LX-WordNetBrowser-master/webapp/webapp/urls.py", line 18, in <module>
    from search import urls
ModuleNotFoundError: No module named 'search'

I am getting error in url.pl file that's at from search import urls.

**Comment by RubenBranco** [comment]
Hi mdp.

Do you have the search folder in your LX-WordNetBrowser-master/webapp/ folder? Also, did you modify the settings to include search as an installed application? If you don't have either then use this to guide you through the installation: https://lx-wordnetbrowser.readthedocs.io/en/latest/installation.html
If those aren't the issues, we'll look into what else could be causing this.

**Comment by mdp0999** [comment]
Hello RubenBranco,
                                  Thanks for your reply and  I copied the files(doc, my wordnet, pluricentric) into webapp after executing the command "django-adming.py startproject webapp"........... later I did the configuration step by copying and pasting the code in files settings.py, urls.py. Later I struck at WordNet Content Delivery Server step
while I run the command "wordnet_server.py [PORT] [BROWSER_PATH] [BROWSER_TYPE]" I am getting below error:

mdp@mdp-Inspiron-N5110:~/LX-WordNetBrowser-master/webapp/pluricentric$ python wordnet_server.py 1111 $PWD pluricentric
WordNet content loaded
Tab content loaded
Pair content loaded
127.0.0.1 - - [13/Dec/2017 17:37:29] code 501, message Unsupported method ('GET')
127.0.0.1 - - [13/Dec/2017 17:37:29] "GET / HTTP/1.1" 501 -
127.0.0.1 - - [13/Dec/2017 17:37:30] code 501, message Unsupported method ('GET')
127.0.0.1 - - [13/Dec/2017 17:37:30] "GET /favicon.ico HTTP/1.1" 501 -
127.0.0.1 - - [13/Dec/2017 17:39:19] code 501, message Unsupported method ('GET')
127.0.0.1 - - [13/Dec/2017 17:39:19] "GET /admin/ HTTP/1.1" 501 -
127.0.0.1 - - [13/Dec/2017 17:39:19] code 501, message Unsupported method ('GET')
127.0.0.1 - - [13/Dec/2017 17:39:19] "GET /favicon.ico HTTP/1.1" 501 -

Please help me to install this. 
If it is possible give brief explaination of installation process with screenshots.

**Comment by RubenBranco** [comment]
Hi mdp.

I'll try and give a brief explanation. I believe screenshots won't really help since this is text based but if after following this brief explanation you're still having problems, I will make a screenshot by screenshot explanation, so let me know if it worked for you!

First download the zip and extract it somewhere. I cd'd into the folder and created a new virtual environment, just personal choice, you don't have to do it. You can do it by running `virtualenv .`. To activate it run source bin/activate

Then we'll install the dependancies by running `pip3 install -r requirements.txt` and let it install them.

Then create a new django app by running the command: `django-admin.py startproject webapp`

This will create a webapp folder with the project. Now go into pluricentric folder and copy the contents into webapp(Be careful because inside webapp there's another folder webapp, this is **NOT** where you want them).

Now go into webapp/webapp/settings.py and edit the following:

- add 'search' into the list in INSTALLED_APPS
- At the end paste this code:

STATICFILES_DIRS = [
os.path.join(BASE_DIR, "static"),
]

STATIC_URL = '/static/'

If STATIC_URL is already there, which it probably is, then eliminate duplicates.

Now edit the file /webapp/webapp/urls.py by pasting the following:

from django.conf.urls import include, url
from django.contrib import admin
from search import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(urls)),

]

For the WN CDN, it seems like you were able to run it, all you have to do is run it with the structure provided and be sure you give the right folder, you should be giving the path to your webapp project folder.

Make sure to go into your /search/views.py and search for the variable wordnet_server and edit the port. It's running on 9004 on the script, but you can change it to whatever port you set it, I can see you used 1111 so just substitute it.

Now run the following command: `python3 manage.py migrate`

And then run `python3 manage.py runserver` and it should be working fine. I re-installed it just to be safe and I was able to run without any problems.

Do let me know if you were able to!

**Comment by mdp0999** [comment]
Thanks RubenBranco.............. I finished installation

**Comment by mdp0999** [comment]
Hi RubenBranco............. I had done installation and I have gone through few pages of developement. I didn't understand it's structure to proceede development. Could you help me to start working on this??? I am very interested to participate this research bcz I need telugu wordnet for my research.
I think it's following transform and merge method........ so could you explian me where I start to work and develope telugu wordnet.
and I am ready to help you for Dravidian langauges wordnet.

**Comment by RubenBranco** [comment]
Hi. Perhaps you may have misinterpreted the tools intention or maybe I am misinterpreting your intent. This is a wordnet browser for a web view of an already developed wordnet. This is not a editor that will allow you to build one, it is simply for viewing and searching purposes. 

Perhaps you're looking for an editor?

**Comment by mdp0999** [comment]
yeah it's my mistake .........ok and leave that topic and I want to develope wordnet for Telugu and other dravidian languages....... So, will you help me to build wordnet?? 

if you help me this, I will contribute all south indian language for u.

**Comment by mdp0999** [comment]
![adverb](https://user-images.githubusercontent.com/26684241/34028716-e389e624-e18a-11e7-92a6-e460acf8e8f5.png)
![datatxt](https://user-images.githubusercontent.com/26684241/34028717-e3cb8a84-e18a-11e7-8cb1-e82940ce3075.png)
![index_txt](https://user-images.githubusercontent.com/26684241/34028718-e3f66010-e18a-11e7-82bb-c777b955bc43.png)
![onto_txt](https://user-images.githubusercontent.com/26684241/34028719-e420d8e0-e18a-11e7-86d7-9421271267cc.png)



If it is possible, will u give brief description of wordnet development step by step. I have gone through so many articles but I didn't get the development process..........I have doubts on generation of files noun, verb, adj and adv and their index files. If I generate this files, I will able to finish this project. Could you give brief discussion of this files generations and Is there any programming for this files generation and syntax mapping??????? Please help in this part :) ........... I have hindi generated files same like that i want to generate this files into dravidian languages. I attach this files names screen shots and files also. please explain me this files structure and I am little confusing their numbering(index and offset numbers).
![files](https://user-images.githubusercontent.com/26684241/34028611-4d8b68fa-e18a-11e7-9b78-9693483a1e58.png)

**Comment by RubenBranco** [comment]
Hi mdp.

I have yet to work with wordnet generation so I'm afraid I'm not going to be able to help you with your project in that way. As for how the files are structured, here's some documentation that you can take a look at that perfectly describes the structure: https://wordnet.princeton.edu/man/wndb.5WN.html

We're going a bit off topic in terms of the initial error and that one has been resolved so I'm going to close this issue and tag it as resolved.

If you have any other issues, feel free to create a new one. If you need any help not related to the browser, feel free to email me, my email is available on my page.

Thank you!
